// <auto-generated />
using LibraryManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251219173418_addImageUrlToBook")]
    partial class addImageUrlToBook
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("LibraryManagementSystem.Models.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Likes")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Author = "Author A1",
                            CategoryId = 1,
                            Description = "First action book",
                            ImageUrl = "",
                            Likes = 10,
                            Price = 100.0,
                            Review = "Sample Review 1",
                            Title = "Action Book 1"
                        },
                        new
                        {
                            ID = 2,
                            Author = "Author A2",
                            CategoryId = 1,
                            Description = "Second action book",
                            ImageUrl = "",
                            Likes = 15,
                            Price = 120.0,
                            Review = "Sample Review 2",
                            Title = "Action Book 2"
                        },
                        new
                        {
                            ID = 3,
                            Author = "Author A3",
                            CategoryId = 1,
                            Description = "Third action book",
                            ImageUrl = "",
                            Likes = 20,
                            Price = 150.0,
                            Review = "Sample Review 3",
                            Title = "Action Book 3"
                        },
                        new
                        {
                            ID = 4,
                            Author = "Author S1",
                            CategoryId = 2,
                            Description = "First scifi book",
                            ImageUrl = "",
                            Likes = 12,
                            Price = 230.0,
                            Review = "Sample review 1",
                            Title = "SciFi Book 1"
                        },
                        new
                        {
                            ID = 5,
                            Author = "Author S2",
                            CategoryId = 2,
                            Description = "Second scifi book",
                            ImageUrl = "",
                            Likes = 18,
                            Price = 230.0,
                            Review = "Sample review 3",
                            Title = "SciFi Book 2"
                        },
                        new
                        {
                            ID = 6,
                            Author = "Author S3",
                            CategoryId = 2,
                            Description = "Third scifi book",
                            ImageUrl = "",
                            Likes = 22,
                            Price = 230.0,
                            Review = "Sample review 4",
                            Title = "SciFi Book 3"
                        },
                        new
                        {
                            ID = 7,
                            Author = "Author N1",
                            CategoryId = 3,
                            Description = "First non fiction book",
                            ImageUrl = "",
                            Likes = 8,
                            Price = 450.5,
                            Review = "Sample review book 1",
                            Title = "Non Fiction Book 1"
                        },
                        new
                        {
                            ID = 8,
                            Author = "Author N2",
                            CategoryId = 3,
                            Description = "Second non fiction book",
                            ImageUrl = "",
                            Likes = 14,
                            Price = 600.0,
                            Review = "Sample review book 2",
                            Title = "Non Fiction Book 2"
                        },
                        new
                        {
                            ID = 9,
                            Author = "Author N3",
                            CategoryId = 3,
                            Description = "Third non fiction book",
                            ImageUrl = "",
                            Likes = 19,
                            Price = 580.0,
                            Review = "Sample review book 3",
                            Title = "Non Fiction Book 3"
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 3,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 1,
                            Name = "Non Fiction"
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.Book", b =>
                {
                    b.HasOne("LibraryManagementSystem.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
